---
- hosts: all
  become: yes
  gather_facts: False
  pre_tasks:
  - name: Install python for Ansible
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    changed_when: False
  - setup: # aka gather_facts
  tasks:
  - name: update packages
    apt:
      update_cache: yes
  - name: Ensure Apache is running
    apt:
      name: apache2
      state: present
